services:
  mysql:
    image: mysql:8.4
    container_name: vista_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vista_db
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: vista_api
    # IMPORTANT: inside Docker network, use host 'mysql' not 'localhost'
    environment:
      DATABASE_URL: mysql://root:rootpassword@mysql:3306/vista_db
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    # optional: live reload in containers is trickier; for pure prod image leave volumes off.
    # For dev hot-reload you'd run locally with npm run dev instead of this service.

volumes:
  db_data:
